### ISSUE TITLE
Docker Container Requirements

### ISSUE THREAD

**Issue by srfrew** [UBC-MDS/fifa-potential#12]
Discussion for docker containers! To be linked to various pull requests. 

Current plan: 

- [x] Develop Dockerfile
- [x] Implement publishing on push to DockerHub with GitHub Actions
- [x] Add Docker Compose file for seamless launching
- [x] update readme

**Comment by srfrew** [comment]
Dockerfile is developed! Would folks be able to test the build? 

```
docker build --tag fifa_potential:latest .
docker run --rm -it -p 8888:8888 fifa_potential:latest
```

Once this is merged I'll implement the workflows within `main` and move to docker compose

**Comment by srfrew** [comment]
Next step! GitHub Actions deployment

**Comment by srfrew** [comment]
GitHub Actions completed, a test workflow as created and it will run on every change to `Dockerfile`

On to Docker Compose

**Comment by srfrew** [comment]
Docker compose completed. Next steps (eventually) would be to update the readme

- [x] update readme

**Comment by meretelutz** [comment]
I can update the Readme!

**Comment by meretelutz** [comment]
Updated!

**Comment by WaleedMahmood1** [comment]
If it's finalized, should I accept the pull request for the addition of the docker instructions in the `README`?
