### ISSUE TITLE
Environment file versions

### ISSUE THREAD

**Issue by srfrew** [UBC-MDS/fifa-potential#14]
I've noticed that our environment files doesn't contain pinned versions. I believe an earlier revision had this and missed the change. 

Can we move back to pinned versions to ensure reproducibility?

**Comment by srfrew** [comment]
@meretelutz

**Comment by meretelutz** [comment]
Good catch! I'll open up a new branch and add the package versions back in

**Comment by meretelutz** [comment]
Updated the file, please test it out on y'all's machines and let me know if any issues come up!

**Comment by meretelutz** [comment]
Run this line of code when you are in your local version of the repo `conda env create --file environment.yaml`
