### ISSUE TITLE
Division of functions to modularize

### ISSUE THREAD

**Issue by jbarns14** [UBC-MDS/fifa-potential#17]
Respond here with your plan for a function to modularize.

**Comment by meretelutz** [comment]
I'm going to work on writing a function that takes in a list of models and conducts cross-validation, returning fit time, score time, training score, and test score. It will be adapted from Varada's mean_std_cross_val_scores() function found here: https://pages.github.ubc.ca/MDS-2023-24/DSCI_571_sup-learn-1_students/lectures/02_ml-fundamentals.html?highlight=mean_std_cross_val_scores

I've opened up a branch called cross-validation-function and will be working on it there

**Comment by jbarns14** [comment]
I'm going to modularize a function to create the preprocessor given the lists of types of features (numeric, passthrough, categorical, etc).

I opened a branch called preprocessor_function and will be working on it there.

**Comment by WaleedMahmood1** [comment]
Sounds good everyone! I am going to work on modularizing a function to do the EDA (at least the graphing), using altair.
I am going to open up a branch called `eda_function` and work on this there.

**Comment by WaleedMahmood1** [comment]
Format to follow for the docstring:

def plot_numeric_distributions(data, target, numeric_features=None):
    """
    Plot histograms for all numeric features in the dataset.

    Parameters:
    - data (DataFrame): the dataset
    - target (str): name of the target variable
    - numeric_features (list, optional): list of names of the numeric features.
    """

**Comment by meretelutz** [comment]
All functions are passing their tests and all branches have been merged so I am closing this issue! 🤩
