### ISSUE TITLE
Tests for Modularized functions are written up and ready to be submitted

### ISSUE THREAD

**Issue by WaleedMahmood1** [UBC-MDS/fifa-potential#22]
I could only think up of 3 relevant tests to add for the visualization code. I wrote:
- one to check if the graph is of the right type.
- y-axis type is correct.
- the features that the graphs are being created for are correct (i.e. altair is only repeating for numeric features).

I tried writing a test to check whether the coloring/grouping of the data is being done on the `target` variable or not, but I couldn't figure it out... same with whether the y-axis label is `Frequency` or not.

I cannot think of any other tests. If perhaps someone could recommend any other ideas, I can add a test if its possible.

If not, then I guess 3 tests are all that are possible for visualizations.

**Comment by meretelutz** [comment]
I think those should be sufficient! Charts are tricky. But if anyone else has any ideas?
