### ISSUE TITLE
Week 3 To-Dos

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/fifa-potential#28]
1. Abstract more code from your literate code document (*.ipynb, *.Rmd, or .qmd) to scripts (e.g., .R or .py)
Steps to make scripts for:
- [x] 01_load_clean_tidy
- [x] 02_eda_figures
- [x] 03_preprocessing
- [x] 04_model_selection
- [x] 05_hyperparameter_scoring

2. Edit your literate code document (*.ipynb, *Qmd or *.Rmd) so that it’s sole job is to narrate your analysis, display your analysis artifacts (i.e., figures and tables), and nicely format the report

3. Write bash script to run all scripts (baby makefile)

4. Update your project’s computational environment as you add dependencies to your project

5. Submit

**Comment by jbarns14** [comment]
Step 1 - making the scripts done

**Comment by srfrew** [comment]
I was reading the requirements for Milestone 3 and I think we need to export our final model into the results folder!

**Comment by meretelutz** [comment]
Do you mean the model object itself? Does it say that explicitly in the instructions? I think we were hoping to avoid having to do that and deal with pickles

**Comment by srfrew** [comment]
I noticed that Tiff's had them. 

Overall, I've completed docstrings, black formatting, bash script pipeline, and small readme tweaks in the bash-makefile branch #35 

I think things are ready for review and merge!

**Comment by srfrew** [comment]
Submitted! The notebook was updated, github pages configured, and readme updated with new links and to-dos

**Comment by meretelutz** [comment]
Closing this issue as we submitted Milestone 3
