### ISSUE TITLE
Analysis component (confusion matrix)

### ISSUE THREAD

**Issue by WaleedMahmood1** [UBC-MDS/fifa-potential#9]
I am wondering, if we should have a confusion matrix added into our analysis. For example, we could perhaps look into if we have any type 1 or type 2 errors.

**Comment by srfrew** [comment]
I think that would be great except that we don't have a binary predictor - I'm not sure if we can extend a confusion matrix to multiple dimensions

**Comment by meretelutz** [comment]
Yeah, I don't think we know how to do a confusion matrix with a target class that has multiple categories. But maybe we should brainstorm ways to incorporate other metrics!
